# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoteCam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRemoteCam.proto\x12\x0eRemoteCamProto\"%\n\x0fGetImageRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"l\n\x10GetImageResponse\x12\x13\n\x0bresponse_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\x05\x63olor\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05\x64\x65pth\x18\x05 \x03(\x05\x42\x02\x10\x01\x32\x61\n\x0eRemoteCamProto\x12O\n\x08GetImage\x12\x1f.RemoteCamProto.GetImageRequest\x1a .RemoteCamProto.GetImageResponse\"\x00\x42@\n%io.grpc.custom.Disinfection.RemoteCamB\x0eRemoteCamProtoP\x01\xa2\x02\x04\x46\x44\x44Ob\x06proto3')



_GETIMAGEREQUEST = DESCRIPTOR.message_types_by_name['GetImageRequest']
_GETIMAGERESPONSE = DESCRIPTOR.message_types_by_name['GetImageResponse']
GetImageRequest = _reflection.GeneratedProtocolMessageType('GetImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGEREQUEST,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageRequest)
  })
_sym_db.RegisterMessage(GetImageRequest)

GetImageResponse = _reflection.GeneratedProtocolMessageType('GetImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETIMAGERESPONSE,
  '__module__' : 'RemoteCam_pb2'
  # @@protoc_insertion_point(class_scope:RemoteCamProto.GetImageResponse)
  })
_sym_db.RegisterMessage(GetImageResponse)

_REMOTECAMPROTO = DESCRIPTOR.services_by_name['RemoteCamProto']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%io.grpc.custom.Disinfection.RemoteCamB\016RemoteCamProtoP\001\242\002\004FDDO'
  _GETIMAGERESPONSE.fields_by_name['color']._options = None
  _GETIMAGERESPONSE.fields_by_name['color']._serialized_options = b'\020\001'
  _GETIMAGERESPONSE.fields_by_name['depth']._options = None
  _GETIMAGERESPONSE.fields_by_name['depth']._serialized_options = b'\020\001'
  _GETIMAGEREQUEST._serialized_start=35
  _GETIMAGEREQUEST._serialized_end=72
  _GETIMAGERESPONSE._serialized_start=74
  _GETIMAGERESPONSE._serialized_end=182
  _REMOTECAMPROTO._serialized_start=184
  _REMOTECAMPROTO._serialized_end=281
# @@protoc_insertion_point(module_scope)
