# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import DisinfectionOperation_pb2 as DisinfectionOperation__pb2


class DisinfectionOperationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoDisinfection = channel.unary_unary(
                '/DisinfectionOperation.DisinfectionOperation/DoDisinfection',
                request_serializer=DisinfectionOperation__pb2.DoDisinfectionRequest.SerializeToString,
                response_deserializer=DisinfectionOperation__pb2.DoDisinfectionResponse.FromString,
                )
        self.DoDisinfectionComplete = channel.unary_unary(
                '/DisinfectionOperation.DisinfectionOperation/DoDisinfectionComplete',
                request_serializer=DisinfectionOperation__pb2.DoDisinfectionCompleteRequest.SerializeToString,
                response_deserializer=DisinfectionOperation__pb2.DoDisinfectionCompleteResponse.FromString,
                )


class DisinfectionOperationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoDisinfection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoDisinfectionComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisinfectionOperationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoDisinfection': grpc.unary_unary_rpc_method_handler(
                    servicer.DoDisinfection,
                    request_deserializer=DisinfectionOperation__pb2.DoDisinfectionRequest.FromString,
                    response_serializer=DisinfectionOperation__pb2.DoDisinfectionResponse.SerializeToString,
            ),
            'DoDisinfectionComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.DoDisinfectionComplete,
                    request_deserializer=DisinfectionOperation__pb2.DoDisinfectionCompleteRequest.FromString,
                    response_serializer=DisinfectionOperation__pb2.DoDisinfectionCompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DisinfectionOperation.DisinfectionOperation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DisinfectionOperation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoDisinfection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DisinfectionOperation.DisinfectionOperation/DoDisinfection',
            DisinfectionOperation__pb2.DoDisinfectionRequest.SerializeToString,
            DisinfectionOperation__pb2.DoDisinfectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoDisinfectionComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DisinfectionOperation.DisinfectionOperation/DoDisinfectionComplete',
            DisinfectionOperation__pb2.DoDisinfectionCompleteRequest.SerializeToString,
            DisinfectionOperation__pb2.DoDisinfectionCompleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
