# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskPlanner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskPlanner.proto',
  package='TaskPlanner',
  syntax='proto3',
  serialized_options=b'\n,io.grpc.custom.FloorDisinfection.TaskPlannerB\020TaskPlannerProtoP\001\242\002\004FDTP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11TaskPlanner.proto\x12\x0bTaskPlanner\"+\n\x13GetRobotInfoRequest\x12\x14\n\x0crequest_flag\x18\x01 \x01(\x05\"Z\n\x14GetRobotInfoResponse\x12\r\n\x05width\x18\x01 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x01\x12\x0e\n\x06height\x18\x03 \x01(\x01\x12\t\n\x01x\x18\x04 \x01(\x01\x12\t\n\x01y\x18\x05 \x01(\x01\"Y\n\x0bobject_info\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x13\n\x0bobject_name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x65nter_x\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x65nter_y\x18\x04 \x01(\x01\"F\n\x15\x44oDisinfectionRequest\x12-\n\x0bobject_list\x18\x01 \x03(\x0b\x32\x18.TaskPlanner.object_info\"/\n\x16\x44oDisinfectionResponse\x12\x15\n\rresponse_flag\x18\x01 \x01(\x05\"+\n\x13RunningStateRequest\x12\x14\n\x0crequest_flag\x18\x01 \x01(\x05\")\n\x14RunningStateResponse\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x32\x9d\x02\n\x0cTaskExecutor\x12U\n\x0cGetRobotInfo\x12 .TaskPlanner.GetRobotInfoRequest\x1a!.TaskPlanner.GetRobotInfoResponse\"\x00\x12[\n\x0e\x44oDisinfection\x12\".TaskPlanner.DoDisinfectionRequest\x1a#.TaskPlanner.DoDisinfectionResponse\"\x00\x12Y\n\x10GetRunningStatus\x12 .TaskPlanner.RunningStateRequest\x1a!.TaskPlanner.RunningStateResponse\"\x00\x42I\n,io.grpc.custom.FloorDisinfection.TaskPlannerB\x10TaskPlannerProtoP\x01\xa2\x02\x04\x46\x44TPb\x06proto3'
)




_GETROBOTINFOREQUEST = _descriptor.Descriptor(
  name='GetRobotInfoRequest',
  full_name='TaskPlanner.GetRobotInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_flag', full_name='TaskPlanner.GetRobotInfoRequest.request_flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=77,
)


_GETROBOTINFORESPONSE = _descriptor.Descriptor(
  name='GetRobotInfoResponse',
  full_name='TaskPlanner.GetRobotInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='TaskPlanner.GetRobotInfoResponse.width', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='TaskPlanner.GetRobotInfoResponse.depth', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='TaskPlanner.GetRobotInfoResponse.height', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='TaskPlanner.GetRobotInfoResponse.x', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='TaskPlanner.GetRobotInfoResponse.y', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=169,
)


_OBJECT_INFO = _descriptor.Descriptor(
  name='object_info',
  full_name='TaskPlanner.object_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='TaskPlanner.object_info.object_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object_name', full_name='TaskPlanner.object_info.object_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center_x', full_name='TaskPlanner.object_info.center_x', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center_y', full_name='TaskPlanner.object_info.center_y', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=260,
)


_DODISINFECTIONREQUEST = _descriptor.Descriptor(
  name='DoDisinfectionRequest',
  full_name='TaskPlanner.DoDisinfectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_list', full_name='TaskPlanner.DoDisinfectionRequest.object_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=332,
)


_DODISINFECTIONRESPONSE = _descriptor.Descriptor(
  name='DoDisinfectionResponse',
  full_name='TaskPlanner.DoDisinfectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_flag', full_name='TaskPlanner.DoDisinfectionResponse.response_flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=381,
)


_RUNNINGSTATEREQUEST = _descriptor.Descriptor(
  name='RunningStateRequest',
  full_name='TaskPlanner.RunningStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_flag', full_name='TaskPlanner.RunningStateRequest.request_flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=426,
)


_RUNNINGSTATERESPONSE = _descriptor.Descriptor(
  name='RunningStateResponse',
  full_name='TaskPlanner.RunningStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='TaskPlanner.RunningStateResponse.object_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=469,
)

_DODISINFECTIONREQUEST.fields_by_name['object_list'].message_type = _OBJECT_INFO
DESCRIPTOR.message_types_by_name['GetRobotInfoRequest'] = _GETROBOTINFOREQUEST
DESCRIPTOR.message_types_by_name['GetRobotInfoResponse'] = _GETROBOTINFORESPONSE
DESCRIPTOR.message_types_by_name['object_info'] = _OBJECT_INFO
DESCRIPTOR.message_types_by_name['DoDisinfectionRequest'] = _DODISINFECTIONREQUEST
DESCRIPTOR.message_types_by_name['DoDisinfectionResponse'] = _DODISINFECTIONRESPONSE
DESCRIPTOR.message_types_by_name['RunningStateRequest'] = _RUNNINGSTATEREQUEST
DESCRIPTOR.message_types_by_name['RunningStateResponse'] = _RUNNINGSTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRobotInfoRequest = _reflection.GeneratedProtocolMessageType('GetRobotInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETROBOTINFOREQUEST,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.GetRobotInfoRequest)
  })
_sym_db.RegisterMessage(GetRobotInfoRequest)

GetRobotInfoResponse = _reflection.GeneratedProtocolMessageType('GetRobotInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETROBOTINFORESPONSE,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.GetRobotInfoResponse)
  })
_sym_db.RegisterMessage(GetRobotInfoResponse)

object_info = _reflection.GeneratedProtocolMessageType('object_info', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT_INFO,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.object_info)
  })
_sym_db.RegisterMessage(object_info)

DoDisinfectionRequest = _reflection.GeneratedProtocolMessageType('DoDisinfectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DODISINFECTIONREQUEST,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.DoDisinfectionRequest)
  })
_sym_db.RegisterMessage(DoDisinfectionRequest)

DoDisinfectionResponse = _reflection.GeneratedProtocolMessageType('DoDisinfectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DODISINFECTIONRESPONSE,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.DoDisinfectionResponse)
  })
_sym_db.RegisterMessage(DoDisinfectionResponse)

RunningStateRequest = _reflection.GeneratedProtocolMessageType('RunningStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGSTATEREQUEST,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.RunningStateRequest)
  })
_sym_db.RegisterMessage(RunningStateRequest)

RunningStateResponse = _reflection.GeneratedProtocolMessageType('RunningStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGSTATERESPONSE,
  '__module__' : 'TaskPlanner_pb2'
  # @@protoc_insertion_point(class_scope:TaskPlanner.RunningStateResponse)
  })
_sym_db.RegisterMessage(RunningStateResponse)


DESCRIPTOR._options = None

_TASKEXECUTOR = _descriptor.ServiceDescriptor(
  name='TaskExecutor',
  full_name='TaskPlanner.TaskExecutor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=472,
  serialized_end=757,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRobotInfo',
    full_name='TaskPlanner.TaskExecutor.GetRobotInfo',
    index=0,
    containing_service=None,
    input_type=_GETROBOTINFOREQUEST,
    output_type=_GETROBOTINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoDisinfection',
    full_name='TaskPlanner.TaskExecutor.DoDisinfection',
    index=1,
    containing_service=None,
    input_type=_DODISINFECTIONREQUEST,
    output_type=_DODISINFECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRunningStatus',
    full_name='TaskPlanner.TaskExecutor.GetRunningStatus',
    index=2,
    containing_service=None,
    input_type=_RUNNINGSTATEREQUEST,
    output_type=_RUNNINGSTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKEXECUTOR)

DESCRIPTOR.services_by_name['TaskExecutor'] = _TASKEXECUTOR

# @@protoc_insertion_point(module_scope)
