# -*- coding: utf-8 -*- 

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IndyGeneral.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IndyGeneral.proto',
  package='IndyFramework.rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11IndyGeneral.proto\x12\x11IndyFramework.rpc\"\x0e\n\x0c\x45mptyMessage\"\x1f\n\x0e\x42ooleanMessage\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1f\n\x0eIntegerMessage\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1e\n\rDoubleMessage\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1c\n\rStringMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"2\n\x14\x42ooleanStringMessage\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"2\n\x14IntegerStringMessage\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"1\n\x13\x44oubleStringMessage\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0b\n\x03msg\x18\x02 \x01(\t\"&\n\x15\x44oubleRepeatedMessage\x12\r\n\x05value\x18\x01 \x03(\x01\x62\x06proto3')
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='IndyFramework.rpc.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=54,
)


_BOOLEANMESSAGE = _descriptor.Descriptor(
  name='BooleanMessage',
  full_name='IndyFramework.rpc.BooleanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.BooleanMessage.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=87,
)


_INTEGERMESSAGE = _descriptor.Descriptor(
  name='IntegerMessage',
  full_name='IndyFramework.rpc.IntegerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.IntegerMessage.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=120,
)


_DOUBLEMESSAGE = _descriptor.Descriptor(
  name='DoubleMessage',
  full_name='IndyFramework.rpc.DoubleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.DoubleMessage.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=152,
)


_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='IndyFramework.rpc.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.rpc.StringMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=182,
)


_BOOLEANSTRINGMESSAGE = _descriptor.Descriptor(
  name='BooleanStringMessage',
  full_name='IndyFramework.rpc.BooleanStringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.BooleanStringMessage.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.rpc.BooleanStringMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=234,
)


_INTEGERSTRINGMESSAGE = _descriptor.Descriptor(
  name='IntegerStringMessage',
  full_name='IndyFramework.rpc.IntegerStringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.IntegerStringMessage.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.rpc.IntegerStringMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=286,
)


_DOUBLESTRINGMESSAGE = _descriptor.Descriptor(
  name='DoubleStringMessage',
  full_name='IndyFramework.rpc.DoubleStringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.DoubleStringMessage.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='IndyFramework.rpc.DoubleStringMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=337,
)


_DOUBLEREPEATEDMESSAGE = _descriptor.Descriptor(
  name='DoubleRepeatedMessage',
  full_name='IndyFramework.rpc.DoubleRepeatedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='IndyFramework.rpc.DoubleRepeatedMessage.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=377,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['BooleanMessage'] = _BOOLEANMESSAGE
DESCRIPTOR.message_types_by_name['IntegerMessage'] = _INTEGERMESSAGE
DESCRIPTOR.message_types_by_name['DoubleMessage'] = _DOUBLEMESSAGE
DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
DESCRIPTOR.message_types_by_name['BooleanStringMessage'] = _BOOLEANSTRINGMESSAGE
DESCRIPTOR.message_types_by_name['IntegerStringMessage'] = _INTEGERSTRINGMESSAGE
DESCRIPTOR.message_types_by_name['DoubleStringMessage'] = _DOUBLESTRINGMESSAGE
DESCRIPTOR.message_types_by_name['DoubleRepeatedMessage'] = _DOUBLEREPEATEDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.EmptyMessage)
  ))
_sym_db.RegisterMessage(EmptyMessage)

BooleanMessage = _reflection.GeneratedProtocolMessageType('BooleanMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.BooleanMessage)
  ))
_sym_db.RegisterMessage(BooleanMessage)

IntegerMessage = _reflection.GeneratedProtocolMessageType('IntegerMessage', (_message.Message,), dict(
  DESCRIPTOR = _INTEGERMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.IntegerMessage)
  ))
_sym_db.RegisterMessage(IntegerMessage)

DoubleMessage = _reflection.GeneratedProtocolMessageType('DoubleMessage', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLEMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.DoubleMessage)
  ))
_sym_db.RegisterMessage(DoubleMessage)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), dict(
  DESCRIPTOR = _STRINGMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.StringMessage)
  ))
_sym_db.RegisterMessage(StringMessage)

BooleanStringMessage = _reflection.GeneratedProtocolMessageType('BooleanStringMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANSTRINGMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.BooleanStringMessage)
  ))
_sym_db.RegisterMessage(BooleanStringMessage)

IntegerStringMessage = _reflection.GeneratedProtocolMessageType('IntegerStringMessage', (_message.Message,), dict(
  DESCRIPTOR = _INTEGERSTRINGMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.IntegerStringMessage)
  ))
_sym_db.RegisterMessage(IntegerStringMessage)

DoubleStringMessage = _reflection.GeneratedProtocolMessageType('DoubleStringMessage', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLESTRINGMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.DoubleStringMessage)
  ))
_sym_db.RegisterMessage(DoubleStringMessage)

DoubleRepeatedMessage = _reflection.GeneratedProtocolMessageType('DoubleRepeatedMessage', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLEREPEATEDMESSAGE,
  __module__ = 'IndyGeneral_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.DoubleRepeatedMessage)
  ))
_sym_db.RegisterMessage(DoubleRepeatedMessage)


# @@protoc_insertion_point(module_scope)
