# -*- coding: utf-8 -*- 

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IndyPosition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='IndyPosition.proto',
  package='IndyFramework.rpc.Control',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12IndyPosition.proto\x12\x19IndyFramework.rpc.Control\"\x15\n\x08JointPos\x12\t\n\x01q\x18\x01 \x03(\x01\"\x14\n\x07TaskPos\x12\t\n\x01p\x18\x01 \x03(\x01\"\xb0\x01\n\x0eTaskPosProcess\x12:\n\x07segType\x18\x01 \x01(\x0e\x32).IndyFramework.rpc.Control.ProcessSegType\x12\x30\n\x04pos1\x18\x02 \x01(\x0b\x32\".IndyFramework.rpc.Control.TaskPos\x12\x30\n\x04pos2\x18\x03 \x01(\x0b\x32\".IndyFramework.rpc.Control.TaskPos\"\xf9\x01\n\x08Position\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.IndyFramework.rpc.Control.PositionType\x12\x37\n\x08jointPos\x18\x02 \x01(\x0b\x32#.IndyFramework.rpc.Control.JointPosH\x00\x12\x35\n\x07taskPos\x18\x03 \x01(\x0b\x32\".IndyFramework.rpc.Control.TaskPosH\x00\x12=\n\x08taskPosP\x18\x04 \x01(\x0b\x32).IndyFramework.rpc.Control.TaskPosProcessH\x00\x42\x07\n\x05posAs*z\n\x0cPositionType\x12\x19\n\x15INDY_POS_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13INDY_POS_TYPE_JOINT\x10\x01\x12\x16\n\x12INDY_POS_TYPE_TASK\x10\x02\x12\x1e\n\x1aINDY_POS_TYPE_TASK_PROCESS\x10\x03*R\n\x0eProcessSegType\x12\x1e\n\x1aINDY_PROCESS_SEG_TYPE_LINE\x10\x00\x12 \n\x1cINDY_PROCESS_SEG_TYPE_CIRCLE\x10\x01\x62\x06proto3')
)

_POSITIONTYPE = _descriptor.EnumDescriptor(
  name='PositionType',
  full_name='IndyFramework.rpc.Control.PositionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDY_POS_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_POS_TYPE_JOINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_POS_TYPE_TASK', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_POS_TYPE_TASK_PROCESS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=525,
  serialized_end=647,
)
_sym_db.RegisterEnumDescriptor(_POSITIONTYPE)

PositionType = enum_type_wrapper.EnumTypeWrapper(_POSITIONTYPE)
_PROCESSSEGTYPE = _descriptor.EnumDescriptor(
  name='ProcessSegType',
  full_name='IndyFramework.rpc.Control.ProcessSegType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDY_PROCESS_SEG_TYPE_LINE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_PROCESS_SEG_TYPE_CIRCLE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=649,
  serialized_end=731,
)
_sym_db.RegisterEnumDescriptor(_PROCESSSEGTYPE)

ProcessSegType = enum_type_wrapper.EnumTypeWrapper(_PROCESSSEGTYPE)
INDY_POS_TYPE_UNKNOWN = 0
INDY_POS_TYPE_JOINT = 1
INDY_POS_TYPE_TASK = 2
INDY_POS_TYPE_TASK_PROCESS = 3
INDY_PROCESS_SEG_TYPE_LINE = 0
INDY_PROCESS_SEG_TYPE_CIRCLE = 1



_JOINTPOS = _descriptor.Descriptor(
  name='JointPos',
  full_name='IndyFramework.rpc.Control.JointPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='q', full_name='IndyFramework.rpc.Control.JointPos.q', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=70,
)


_TASKPOS = _descriptor.Descriptor(
  name='TaskPos',
  full_name='IndyFramework.rpc.Control.TaskPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='IndyFramework.rpc.Control.TaskPos.p', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=92,
)


_TASKPOSPROCESS = _descriptor.Descriptor(
  name='TaskPosProcess',
  full_name='IndyFramework.rpc.Control.TaskPosProcess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segType', full_name='IndyFramework.rpc.Control.TaskPosProcess.segType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos1', full_name='IndyFramework.rpc.Control.TaskPosProcess.pos1', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos2', full_name='IndyFramework.rpc.Control.TaskPosProcess.pos2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=271,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='IndyFramework.rpc.Control.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='IndyFramework.rpc.Control.Position.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jointPos', full_name='IndyFramework.rpc.Control.Position.jointPos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taskPos', full_name='IndyFramework.rpc.Control.Position.taskPos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taskPosP', full_name='IndyFramework.rpc.Control.Position.taskPosP', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='posAs', full_name='IndyFramework.rpc.Control.Position.posAs',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=274,
  serialized_end=523,
)

_TASKPOSPROCESS.fields_by_name['segType'].enum_type = _PROCESSSEGTYPE
_TASKPOSPROCESS.fields_by_name['pos1'].message_type = _TASKPOS
_TASKPOSPROCESS.fields_by_name['pos2'].message_type = _TASKPOS
_POSITION.fields_by_name['type'].enum_type = _POSITIONTYPE
_POSITION.fields_by_name['jointPos'].message_type = _JOINTPOS
_POSITION.fields_by_name['taskPos'].message_type = _TASKPOS
_POSITION.fields_by_name['taskPosP'].message_type = _TASKPOSPROCESS
_POSITION.oneofs_by_name['posAs'].fields.append(
  _POSITION.fields_by_name['jointPos'])
_POSITION.fields_by_name['jointPos'].containing_oneof = _POSITION.oneofs_by_name['posAs']
_POSITION.oneofs_by_name['posAs'].fields.append(
  _POSITION.fields_by_name['taskPos'])
_POSITION.fields_by_name['taskPos'].containing_oneof = _POSITION.oneofs_by_name['posAs']
_POSITION.oneofs_by_name['posAs'].fields.append(
  _POSITION.fields_by_name['taskPosP'])
_POSITION.fields_by_name['taskPosP'].containing_oneof = _POSITION.oneofs_by_name['posAs']
DESCRIPTOR.message_types_by_name['JointPos'] = _JOINTPOS
DESCRIPTOR.message_types_by_name['TaskPos'] = _TASKPOS
DESCRIPTOR.message_types_by_name['TaskPosProcess'] = _TASKPOSPROCESS
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.enum_types_by_name['PositionType'] = _POSITIONTYPE
DESCRIPTOR.enum_types_by_name['ProcessSegType'] = _PROCESSSEGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointPos = _reflection.GeneratedProtocolMessageType('JointPos', (_message.Message,), dict(
  DESCRIPTOR = _JOINTPOS,
  __module__ = 'IndyPosition_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.JointPos)
  ))
_sym_db.RegisterMessage(JointPos)

TaskPos = _reflection.GeneratedProtocolMessageType('TaskPos', (_message.Message,), dict(
  DESCRIPTOR = _TASKPOS,
  __module__ = 'IndyPosition_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TaskPos)
  ))
_sym_db.RegisterMessage(TaskPos)

TaskPosProcess = _reflection.GeneratedProtocolMessageType('TaskPosProcess', (_message.Message,), dict(
  DESCRIPTOR = _TASKPOSPROCESS,
  __module__ = 'IndyPosition_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TaskPosProcess)
  ))
_sym_db.RegisterMessage(TaskPosProcess)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'IndyPosition_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.Position)
  ))
_sym_db.RegisterMessage(Position)


# @@protoc_insertion_point(module_scope)
