# -*- coding: utf-8 -*- 

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IndyLocalServices.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IndyGeneral_pb2 as IndyGeneral__pb2
import IndyMotion_pb2 as IndyMotion__pb2
try:
  IndyStates__pb2 = IndyMotion__pb2.IndyStates__pb2
except AttributeError:
  IndyStates__pb2 = IndyMotion__pb2.IndyStates_pb2
try:
  IndyPosition__pb2 = IndyMotion__pb2.IndyPosition__pb2
except AttributeError:
  IndyPosition__pb2 = IndyMotion__pb2.IndyPosition_pb2
try:
  IndyTrajectoryEvent__pb2 = IndyMotion__pb2.IndyTrajectoryEvent__pb2
except AttributeError:
  IndyTrajectoryEvent__pb2 = IndyMotion__pb2.IndyTrajectoryEvent_pb2
try:
  IndyStates__pb2 = IndyMotion__pb2.IndyStates__pb2
except AttributeError:
  IndyStates__pb2 = IndyMotion__pb2.IndyStates_pb2
try:
  IndyMotionProperty__pb2 = IndyMotion__pb2.IndyMotionProperty__pb2
except AttributeError:
  IndyMotionProperty__pb2 = IndyMotion__pb2.IndyMotionProperty_pb2
try:
  IndySafety__pb2 = IndyMotion__pb2.IndySafety__pb2
except AttributeError:
  IndySafety__pb2 = IndyMotion__pb2.IndySafety_pb2
try:
  IndyIOState__pb2 = IndyMotion__pb2.IndyIOState__pb2
except AttributeError:
  IndyIOState__pb2 = IndyMotion__pb2.IndyIOState_pb2
import IndySafety_pb2 as IndySafety__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IndyLocalServices.proto',
  package='IndyFramework.rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17IndyLocalServices.proto\x12\x11IndyFramework.rpc\x1a\x11IndyGeneral.proto\x1a\x10IndyMotion.proto\x1a\x10IndySafety.proto2\xd7\x0b\n\x0f\x43ontrolDirector\x12W\n\x10\x63hangeSpeedRatio\x12 .IndyFramework.rpc.DoubleMessage\x1a\x1f.IndyFramework.rpc.EmptyMessage\"\x00\x12]\n\renqueueMotion\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12\x66\n\x16\x65nqueueMotionAvailable\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12g\n\x17\x65nqueueMotionAcceptable\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12\x65\n\x15\x65nqueuePriorityMotion\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12X\n\nstopMotion\x12%.IndyFramework.rpc.Control.MotionStop\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12[\n\x0b\x65nqueueHome\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12[\n\x0b\x65nqueueZero\x12!.IndyFramework.rpc.Control.Motion\x1a\'.IndyFramework.rpc.Control.MotionResult\"\x00\x12P\n\x08isMoving\x12\x1f.IndyFramework.rpc.EmptyMessage\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12N\n\x06isIdle\x12\x1f.IndyFramework.rpc.EmptyMessage\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12U\n\risMotionEmpty\x12\x1f.IndyFramework.rpc.EmptyMessage\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12T\n\x0cisMotionFull\x12\x1f.IndyFramework.rpc.EmptyMessage\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12\\\n\x12isMotionAcceptable\x12!.IndyFramework.rpc.Control.Motion\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12V\n\x0ewaitMotionDone\x12\x1f.IndyFramework.rpc.EmptyMessage\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12^\n\x14waitMotionAcceptable\x12!.IndyFramework.rpc.Control.Motion\x1a!.IndyFramework.rpc.BooleanMessage\"\x00\x12[\n\x14setMotionWaitTimeout\x12 .IndyFramework.rpc.DoubleMessage\x1a\x1f.IndyFramework.rpc.EmptyMessage\"\x00\x62\x06proto3')
  ,
  dependencies=[IndyGeneral__pb2.DESCRIPTOR,IndyMotion__pb2.DESCRIPTOR,IndySafety__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONTROLDIRECTOR = _descriptor.ServiceDescriptor(
  name='ControlDirector',
  full_name='IndyFramework.rpc.ControlDirector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=1597,
  methods=[
  _descriptor.MethodDescriptor(
    name='changeSpeedRatio',
    full_name='IndyFramework.rpc.ControlDirector.changeSpeedRatio',
    index=0,
    containing_service=None,
    input_type=IndyGeneral__pb2._DOUBLEMESSAGE,
    output_type=IndyGeneral__pb2._EMPTYMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueueMotion',
    full_name='IndyFramework.rpc.ControlDirector.enqueueMotion',
    index=1,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueueMotionAvailable',
    full_name='IndyFramework.rpc.ControlDirector.enqueueMotionAvailable',
    index=2,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueueMotionAcceptable',
    full_name='IndyFramework.rpc.ControlDirector.enqueueMotionAcceptable',
    index=3,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueuePriorityMotion',
    full_name='IndyFramework.rpc.ControlDirector.enqueuePriorityMotion',
    index=4,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopMotion',
    full_name='IndyFramework.rpc.ControlDirector.stopMotion',
    index=5,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTIONSTOP,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueueHome',
    full_name='IndyFramework.rpc.ControlDirector.enqueueHome',
    index=6,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enqueueZero',
    full_name='IndyFramework.rpc.ControlDirector.enqueueZero',
    index=7,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyMotion__pb2._MOTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isMoving',
    full_name='IndyFramework.rpc.ControlDirector.isMoving',
    index=8,
    containing_service=None,
    input_type=IndyGeneral__pb2._EMPTYMESSAGE,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isIdle',
    full_name='IndyFramework.rpc.ControlDirector.isIdle',
    index=9,
    containing_service=None,
    input_type=IndyGeneral__pb2._EMPTYMESSAGE,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isMotionEmpty',
    full_name='IndyFramework.rpc.ControlDirector.isMotionEmpty',
    index=10,
    containing_service=None,
    input_type=IndyGeneral__pb2._EMPTYMESSAGE,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isMotionFull',
    full_name='IndyFramework.rpc.ControlDirector.isMotionFull',
    index=11,
    containing_service=None,
    input_type=IndyGeneral__pb2._EMPTYMESSAGE,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isMotionAcceptable',
    full_name='IndyFramework.rpc.ControlDirector.isMotionAcceptable',
    index=12,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='waitMotionDone',
    full_name='IndyFramework.rpc.ControlDirector.waitMotionDone',
    index=13,
    containing_service=None,
    input_type=IndyGeneral__pb2._EMPTYMESSAGE,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='waitMotionAcceptable',
    full_name='IndyFramework.rpc.ControlDirector.waitMotionAcceptable',
    index=14,
    containing_service=None,
    input_type=IndyMotion__pb2._MOTION,
    output_type=IndyGeneral__pb2._BOOLEANMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setMotionWaitTimeout',
    full_name='IndyFramework.rpc.ControlDirector.setMotionWaitTimeout',
    index=15,
    containing_service=None,
    input_type=IndyGeneral__pb2._DOUBLEMESSAGE,
    output_type=IndyGeneral__pb2._EMPTYMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTROLDIRECTOR)

DESCRIPTOR.services_by_name['ControlDirector'] = _CONTROLDIRECTOR

# @@protoc_insertion_point(module_scope)
