# -*- coding: utf-8 -*- 

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IndyGeneral_pb2 as IndyGeneral__pb2
import IndyIOState_pb2 as IndyIOState__pb2


class IOControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getIOState = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getIOState',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.IOState.FromString,
        )
    self.getDI = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getDI',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.getDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getDO',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.setDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/setDO',
        request_serializer=IndyIOState__pb2.DIOSet.SerializeToString,
        response_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
        )
    self.getAI = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getAI',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.AIOValues.FromString,
        )
    self.getAO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getAO',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.AIOValues.FromString,
        )
    self.setAO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/setAO',
        request_serializer=IndyIOState__pb2.AIOSet.SerializeToString,
        response_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
        )
    self.getSafetyDI = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getSafetyDI',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.getSafetyDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getSafetyDO',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.setSafetyDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/setSafetyDO',
        request_serializer=IndyIOState__pb2.DIOSet.SerializeToString,
        response_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
        )
    self.getEndtoolDI = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getEndtoolDI',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.getEndtoolDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/getEndtoolDO',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyIOState__pb2.DIOValues.FromString,
        )
    self.setEndtoolDO = channel.unary_unary(
        '/IndyFramework.rpc.Com.IOController/setEndtoolDO',
        request_serializer=IndyIOState__pb2.DIOSet.SerializeToString,
        response_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
        )


class IOControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getIOState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setAO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getSafetyDI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getSafetyDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setSafetyDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getEndtoolDI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getEndtoolDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setEndtoolDO(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IOControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getIOState': grpc.unary_unary_rpc_method_handler(
          servicer.getIOState,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.IOState.SerializeToString,
      ),
      'getDI': grpc.unary_unary_rpc_method_handler(
          servicer.getDI,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'getDO': grpc.unary_unary_rpc_method_handler(
          servicer.getDO,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'setDO': grpc.unary_unary_rpc_method_handler(
          servicer.setDO,
          request_deserializer=IndyIOState__pb2.DIOSet.FromString,
          response_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
      ),
      'getAI': grpc.unary_unary_rpc_method_handler(
          servicer.getAI,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.AIOValues.SerializeToString,
      ),
      'getAO': grpc.unary_unary_rpc_method_handler(
          servicer.getAO,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.AIOValues.SerializeToString,
      ),
      'setAO': grpc.unary_unary_rpc_method_handler(
          servicer.setAO,
          request_deserializer=IndyIOState__pb2.AIOSet.FromString,
          response_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
      ),
      'getSafetyDI': grpc.unary_unary_rpc_method_handler(
          servicer.getSafetyDI,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'getSafetyDO': grpc.unary_unary_rpc_method_handler(
          servicer.getSafetyDO,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'setSafetyDO': grpc.unary_unary_rpc_method_handler(
          servicer.setSafetyDO,
          request_deserializer=IndyIOState__pb2.DIOSet.FromString,
          response_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
      ),
      'getEndtoolDI': grpc.unary_unary_rpc_method_handler(
          servicer.getEndtoolDI,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'getEndtoolDO': grpc.unary_unary_rpc_method_handler(
          servicer.getEndtoolDO,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyIOState__pb2.DIOValues.SerializeToString,
      ),
      'setEndtoolDO': grpc.unary_unary_rpc_method_handler(
          servicer.setEndtoolDO,
          request_deserializer=IndyIOState__pb2.DIOSet.FromString,
          response_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IndyFramework.rpc.Com.IOController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
