# -*- coding: utf-8 -*- 

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IndyGeneral_pb2 as IndyGeneral__pb2


class ScriptDirectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.startProgram = channel.unary_unary(
        '/IndyFramework.rpc.Script.ScriptDirector/startProgram',
        request_serializer=IndyGeneral__pb2.StringMessage.SerializeToString,
        response_deserializer=IndyGeneral__pb2.BooleanMessage.FromString,
        )
    self.stopProgram = channel.unary_unary(
        '/IndyFramework.rpc.Script.ScriptDirector/stopProgram',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyGeneral__pb2.BooleanMessage.FromString,
        )
    self.pauseProgram = channel.unary_unary(
        '/IndyFramework.rpc.Script.ScriptDirector/pauseProgram',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyGeneral__pb2.BooleanMessage.FromString,
        )
    self.resumeProgram = channel.unary_unary(
        '/IndyFramework.rpc.Script.ScriptDirector/resumeProgram',
        request_serializer=IndyGeneral__pb2.EmptyMessage.SerializeToString,
        response_deserializer=IndyGeneral__pb2.BooleanMessage.FromString,
        )


class ScriptDirectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def startProgram(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stopProgram(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pauseProgram(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def resumeProgram(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScriptDirectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'startProgram': grpc.unary_unary_rpc_method_handler(
          servicer.startProgram,
          request_deserializer=IndyGeneral__pb2.StringMessage.FromString,
          response_serializer=IndyGeneral__pb2.BooleanMessage.SerializeToString,
      ),
      'stopProgram': grpc.unary_unary_rpc_method_handler(
          servicer.stopProgram,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyGeneral__pb2.BooleanMessage.SerializeToString,
      ),
      'pauseProgram': grpc.unary_unary_rpc_method_handler(
          servicer.pauseProgram,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyGeneral__pb2.BooleanMessage.SerializeToString,
      ),
      'resumeProgram': grpc.unary_unary_rpc_method_handler(
          servicer.resumeProgram,
          request_deserializer=IndyGeneral__pb2.EmptyMessage.FromString,
          response_serializer=IndyGeneral__pb2.BooleanMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IndyFramework.rpc.Script.ScriptDirector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
