# -*- coding: utf-8 -*- 

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IndyTrajectoryProfile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IndyStates_pb2 as IndyStates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IndyTrajectoryProfile.proto',
  package='IndyFramework.rpc.Control',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bIndyTrajectoryProfile.proto\x12\x19IndyFramework.rpc.Control\x1a\x10IndyStates.proto\"r\n\x11TrajectoryProfile\x12\x10\n\x08motionId\x18\x01 \x01(\x05\x12\x35\n\ttrajState\x18\x02 \x01(\x0e\x32\".IndyFramework.rpc.TrajectoryState\x12\x14\n\x0ctrajProgress\x18\x03 \x01(\x01\"T\n\x0f\x42lendingProfile\x12\x41\n\rblendingState\x18\x01 \x01(\x0e\x32*.IndyFramework.rpc.TrajectoryBlendingState\"\xd2\x01\n\x12TrajectoryProfiles\x12>\n\x08profile1\x18\x01 \x01(\x0b\x32,.IndyFramework.rpc.Control.TrajectoryProfile\x12>\n\x08profile2\x18\x02 \x01(\x0b\x32,.IndyFramework.rpc.Control.TrajectoryProfile\x12<\n\x08\x62lending\x18\x03 \x01(\x0b\x32*.IndyFramework.rpc.Control.BlendingProfileb\x06proto3')
  ,
  dependencies=[IndyStates__pb2.DESCRIPTOR,])




_TRAJECTORYPROFILE = _descriptor.Descriptor(
  name='TrajectoryProfile',
  full_name='IndyFramework.rpc.Control.TrajectoryProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motionId', full_name='IndyFramework.rpc.Control.TrajectoryProfile.motionId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajState', full_name='IndyFramework.rpc.Control.TrajectoryProfile.trajState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajProgress', full_name='IndyFramework.rpc.Control.TrajectoryProfile.trajProgress', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=190,
)


_BLENDINGPROFILE = _descriptor.Descriptor(
  name='BlendingProfile',
  full_name='IndyFramework.rpc.Control.BlendingProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blendingState', full_name='IndyFramework.rpc.Control.BlendingProfile.blendingState', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=276,
)


_TRAJECTORYPROFILES = _descriptor.Descriptor(
  name='TrajectoryProfiles',
  full_name='IndyFramework.rpc.Control.TrajectoryProfiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile1', full_name='IndyFramework.rpc.Control.TrajectoryProfiles.profile1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile2', full_name='IndyFramework.rpc.Control.TrajectoryProfiles.profile2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blending', full_name='IndyFramework.rpc.Control.TrajectoryProfiles.blending', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=489,
)

_TRAJECTORYPROFILE.fields_by_name['trajState'].enum_type = IndyStates__pb2._TRAJECTORYSTATE
_BLENDINGPROFILE.fields_by_name['blendingState'].enum_type = IndyStates__pb2._TRAJECTORYBLENDINGSTATE
_TRAJECTORYPROFILES.fields_by_name['profile1'].message_type = _TRAJECTORYPROFILE
_TRAJECTORYPROFILES.fields_by_name['profile2'].message_type = _TRAJECTORYPROFILE
_TRAJECTORYPROFILES.fields_by_name['blending'].message_type = _BLENDINGPROFILE
DESCRIPTOR.message_types_by_name['TrajectoryProfile'] = _TRAJECTORYPROFILE
DESCRIPTOR.message_types_by_name['BlendingProfile'] = _BLENDINGPROFILE
DESCRIPTOR.message_types_by_name['TrajectoryProfiles'] = _TRAJECTORYPROFILES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrajectoryProfile = _reflection.GeneratedProtocolMessageType('TrajectoryProfile', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORYPROFILE,
  __module__ = 'IndyTrajectoryProfile_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TrajectoryProfile)
  ))
_sym_db.RegisterMessage(TrajectoryProfile)

BlendingProfile = _reflection.GeneratedProtocolMessageType('BlendingProfile', (_message.Message,), dict(
  DESCRIPTOR = _BLENDINGPROFILE,
  __module__ = 'IndyTrajectoryProfile_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.BlendingProfile)
  ))
_sym_db.RegisterMessage(BlendingProfile)

TrajectoryProfiles = _reflection.GeneratedProtocolMessageType('TrajectoryProfiles', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORYPROFILES,
  __module__ = 'IndyTrajectoryProfile_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TrajectoryProfiles)
  ))
_sym_db.RegisterMessage(TrajectoryProfiles)


# @@protoc_insertion_point(module_scope)
