# -*- coding: utf-8 -*- 

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IndyTrajectoryEvent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IndyStates_pb2 as IndyStates__pb2

from IndyStates_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='IndyTrajectoryEvent.proto',
  package='IndyFramework.rpc.Control',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19IndyTrajectoryEvent.proto\x12\x19IndyFramework.rpc.Control\x1a\x10IndyStates.proto\"Y\n\x14TrajectoryStateEvent\x12\x41\n\x04type\x18\x01 \x01(\x0e\x32\x33.IndyFramework.rpc.Control.TrajectoryStateEventType\"\xd2\x01\n\x0fTrajectoryEvent\x12<\n\x04type\x18\x01 \x01(\x0e\x32..IndyFramework.rpc.Control.TrajectoryEventType\x12\x15\n\rtargetProfile\x18\x02 \x01(\x05\x12I\n\x0etrajStateEvent\x18\x03 \x01(\x0b\x32/.IndyFramework.rpc.Control.TrajectoryStateEventH\x00\x12\x18\n\x0emotionProgress\x18\x04 \x01(\x01H\x00\x42\x05\n\x03\x61rg*\xef\x01\n\x18TrajectoryStateEventType\x12\x1f\n\x1bINDY_MOTION_TRAJ_EVENT_NONE\x10\x00\x12 \n\x1cINDY_MOTION_TRAJ_EVENT_BEGIN\x10\x01\x12#\n\x1fINDY_MOTION_TRAJ_EVENT_ACC_DONE\x10\x02\x12#\n\x1fINDY_MOTION_TRAJ_EVENT_CRZ_DONE\x10\x03\x12#\n\x1fINDY_MOTION_TRAJ_EVENT_DEC_DONE\x10\x04\x12!\n\x1dINDY_MOTION_TRAJ_EVENT_CANCEL\x10\x05*v\n\x13TrajectoryEventType\x12\x1d\n\x19INDY_TRAJ_EVENT_TYPE_NONE\x10\x00\x12\x1e\n\x1aINDY_TRAJ_EVENT_TYPE_STATE\x10\x01\x12 \n\x1cINDY_TRAJ_EVENT_TYPE_PROCESS\x10\x02P\x00\x62\x06proto3')
  ,
  dependencies=[IndyStates__pb2.DESCRIPTOR,],
  public_dependencies=[IndyStates__pb2.DESCRIPTOR,])

_TRAJECTORYSTATEEVENTTYPE = _descriptor.EnumDescriptor(
  name='TrajectoryStateEventType',
  full_name='IndyFramework.rpc.Control.TrajectoryStateEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_BEGIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_ACC_DONE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_CRZ_DONE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_DEC_DONE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_MOTION_TRAJ_EVENT_CANCEL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=379,
  serialized_end=618,
)
_sym_db.RegisterEnumDescriptor(_TRAJECTORYSTATEEVENTTYPE)

TrajectoryStateEventType = enum_type_wrapper.EnumTypeWrapper(_TRAJECTORYSTATEEVENTTYPE)
_TRAJECTORYEVENTTYPE = _descriptor.EnumDescriptor(
  name='TrajectoryEventType',
  full_name='IndyFramework.rpc.Control.TrajectoryEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDY_TRAJ_EVENT_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_TRAJ_EVENT_TYPE_STATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDY_TRAJ_EVENT_TYPE_PROCESS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=620,
  serialized_end=738,
)
_sym_db.RegisterEnumDescriptor(_TRAJECTORYEVENTTYPE)

TrajectoryEventType = enum_type_wrapper.EnumTypeWrapper(_TRAJECTORYEVENTTYPE)
INDY_MOTION_TRAJ_EVENT_NONE = 0
INDY_MOTION_TRAJ_EVENT_BEGIN = 1
INDY_MOTION_TRAJ_EVENT_ACC_DONE = 2
INDY_MOTION_TRAJ_EVENT_CRZ_DONE = 3
INDY_MOTION_TRAJ_EVENT_DEC_DONE = 4
INDY_MOTION_TRAJ_EVENT_CANCEL = 5
INDY_TRAJ_EVENT_TYPE_NONE = 0
INDY_TRAJ_EVENT_TYPE_STATE = 1
INDY_TRAJ_EVENT_TYPE_PROCESS = 2



_TRAJECTORYSTATEEVENT = _descriptor.Descriptor(
  name='TrajectoryStateEvent',
  full_name='IndyFramework.rpc.Control.TrajectoryStateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='IndyFramework.rpc.Control.TrajectoryStateEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=163,
)


_TRAJECTORYEVENT = _descriptor.Descriptor(
  name='TrajectoryEvent',
  full_name='IndyFramework.rpc.Control.TrajectoryEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='IndyFramework.rpc.Control.TrajectoryEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetProfile', full_name='IndyFramework.rpc.Control.TrajectoryEvent.targetProfile', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajStateEvent', full_name='IndyFramework.rpc.Control.TrajectoryEvent.trajStateEvent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motionProgress', full_name='IndyFramework.rpc.Control.TrajectoryEvent.motionProgress', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='arg', full_name='IndyFramework.rpc.Control.TrajectoryEvent.arg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=166,
  serialized_end=376,
)

_TRAJECTORYSTATEEVENT.fields_by_name['type'].enum_type = _TRAJECTORYSTATEEVENTTYPE
_TRAJECTORYEVENT.fields_by_name['type'].enum_type = _TRAJECTORYEVENTTYPE
_TRAJECTORYEVENT.fields_by_name['trajStateEvent'].message_type = _TRAJECTORYSTATEEVENT
_TRAJECTORYEVENT.oneofs_by_name['arg'].fields.append(
  _TRAJECTORYEVENT.fields_by_name['trajStateEvent'])
_TRAJECTORYEVENT.fields_by_name['trajStateEvent'].containing_oneof = _TRAJECTORYEVENT.oneofs_by_name['arg']
_TRAJECTORYEVENT.oneofs_by_name['arg'].fields.append(
  _TRAJECTORYEVENT.fields_by_name['motionProgress'])
_TRAJECTORYEVENT.fields_by_name['motionProgress'].containing_oneof = _TRAJECTORYEVENT.oneofs_by_name['arg']
DESCRIPTOR.message_types_by_name['TrajectoryStateEvent'] = _TRAJECTORYSTATEEVENT
DESCRIPTOR.message_types_by_name['TrajectoryEvent'] = _TRAJECTORYEVENT
DESCRIPTOR.enum_types_by_name['TrajectoryStateEventType'] = _TRAJECTORYSTATEEVENTTYPE
DESCRIPTOR.enum_types_by_name['TrajectoryEventType'] = _TRAJECTORYEVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrajectoryStateEvent = _reflection.GeneratedProtocolMessageType('TrajectoryStateEvent', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORYSTATEEVENT,
  __module__ = 'IndyTrajectoryEvent_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TrajectoryStateEvent)
  ))
_sym_db.RegisterMessage(TrajectoryStateEvent)

TrajectoryEvent = _reflection.GeneratedProtocolMessageType('TrajectoryEvent', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORYEVENT,
  __module__ = 'IndyTrajectoryEvent_pb2'
  # @@protoc_insertion_point(class_scope:IndyFramework.rpc.Control.TrajectoryEvent)
  ))
_sym_db.RegisterMessage(TrajectoryEvent)


# @@protoc_insertion_point(module_scope)
